main : main.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
	g++ -Wall -std=c++11 -o main main.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

##### TESTS ######

# test_print_creature : test_print_creature.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_print_creature test_print_creature.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

# test_clonage : test_clonage.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_clonage test_clonage.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

# test_yeux : test_yeux.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_yeux test_yeux.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

# test_oreille : test_oreille.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_oreille test_oreille.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

# test_nageoire : test_nageoire.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_nageoire test_nageoire.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

# test_camouflage : test_camouflage.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_camouflage test_camouflage.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

# test_carapace : test_carapace.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_carapace test_carapace.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 

# test_decorateur_multiple : test_decorateur_multiple.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o  Milieu.o Configuration.o CreatureDecorator.o  YeuxDecorator.o  OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o  ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o
# 	g++ -Wall -std=c++11 -o test_decorateur_multiple test_decorateur_multiple.cpp Aquarium.o ConcreteCreatorBestiole.o ICreature.o Milieu.o Configuration.o CreatureDecorator.o YeuxDecorator.o OreilleDecorator.o NageoireDecorator.o CarapaceDecorator.o CamouflageDecorator.o ComportementGregaire.o ComportementKamikaze.o ComportementPeureuse.o ComportementPrevoyante.o  -L /opt/X11/lib -I /opt/X11/include -I . -lX11 -lpthread 


#### FIN TESTS #####


Aquarium.o : Aquarium.h Aquarium.cpp
	g++ -Wall -std=c++11  -c Aquarium.cpp -I /opt/X11/include -I .

ConcreteCreatorBestiole.o : ConcreteCreatorBestiole.h ConcreteCreatorBestiole.cpp
	g++ -Wall -std=c++11  -c ConcreteCreatorBestiole.cpp -I /opt/X11/include -I .

ICreature.o : ICreature.h ICreature.cpp
	g++ -Wall -std=c++11  -c ICreature.cpp -I /opt/X11/include -I .

Milieu.o : Milieu.h Milieu.cpp
	g++ -Wall -std=c++11  -c Milieu.cpp -I /opt/X11/include -I .

Configuration.o : Configuration.h Configuration.cpp
	g++ -Wall -std=c++11  -c Configuration.cpp -I /opt/X11/include -I .

CreatureDecorator.o : CreatureDecorator.h CreatureDecorator.cpp
	g++ -Wall -std=c++11  -c CreatureDecorator.cpp -I /opt/X11/include -I .

YeuxDecorator.o : YeuxDecorator.h YeuxDecorator.cpp
	g++ -Wall -std=c++11  -c YeuxDecorator.cpp -I /opt/X11/include -I .

OreilleDecorator.o : OreilleDecorator.h OreilleDecorator.cpp
	g++ -Wall -std=c++11  -c OreilleDecorator.cpp -I /opt/X11/include -I .

NageoireDecorator.o : NageoireDecorator.h NageoireDecorator.cpp
	g++ -Wall -std=c++11  -c NageoireDecorator.cpp -I /opt/X11/include -I .

CarapaceDecorator.o : CarapaceDecorator.h CarapaceDecorator.cpp
	g++ -Wall -std=c++11  -c CarapaceDecorator.cpp -I /opt/X11/include -I .

CamouflageDecorator.o : CamouflageDecorator.h CamouflageDecorator.cpp
	g++ -Wall -std=c++11  -c CamouflageDecorator.cpp -I /opt/X11/include -I .

ComportementGregaire.o : ComportementGregaire.cpp
	g++ -Wall -std=c++11  -c ComportementGregaire.cpp -I /opt/X11/include -I .

ComportementKamikaze.o : ComportementKamikaze.cpp
	g++ -Wall -std=c++11  -c ComportementKamikaze.cpp -I /opt/X11/include -I .

ComportementPeureuse.o : ComportementPeureuse.cpp
	g++ -Wall -std=c++11  -c ComportementPeureuse.cpp -I /opt/X11/include -I .

ComportementPrevoyante.o : ComportementPrevoyante.cpp
	g++ -Wall -std=c++11  -c ComportementPrevoyante.cpp -I /opt/X11/include -I .
	
clean :
	rm main  *.o



